definitions:
  handler.request:
    properties:
      amount:
        type: number
      code:
        type: string
      currency:
        type: string
      date:
        type: string
      emitter:
        type: string
      receiver:
        type: string
    required:
    - amount
    - code
    - currency
    - date
    - emitter
    - receiver
    type: object
  handler.requestModify:
    properties:
      amount:
        type: number
      code:
        type: string
    required:
    - amount
    - code
    type: object
info:
  contact: {}
  description: this API Handle transactions
  title: Test API
  version: "1.0"
paths:
  /transactions:
    get:
      description: get transactions
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: Object
        "401":
          description: Unauthorized
          schema:
            type: Object
      summary: List transactions
      tags:
      - Transactions
    post:
      consumes:
      - application/json
      description: store a transaction
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: Transaction to store
        in: body
        name: transaction
        required: true
        schema:
          $ref: '#/definitions/handler.request'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: Object
        "400":
          description: Bad Request
          schema:
            type: Object
        "401":
          description: Unauthorized
          schema:
            type: Object
      summary: Store a transaction
      tags:
      - Transactions
  /transactions/{id}:
    delete:
      description: Delete a transaction
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: id
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            type: Object
        "401":
          description: Unauthorized
          schema:
            type: Object
        "404":
          description: Not Found
          schema:
            type: Object
      summary: Delete a transaction
      tags:
      - Transactions
    patch:
      description: Update code and amount of a transaction
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: id
        in: path
        name: id
        required: true
        type: integer
      - description: Transaction to update caode and amount
        in: body
        name: transaction
        required: true
        schema:
          $ref: '#/definitions/handler.requestModify'
      responses:
        "200":
          description: OK
          schema:
            type: Object
        "400":
          description: Bad Request
          schema:
            type: Object
        "401":
          description: Unauthorized
          schema:
            type: Object
        "404":
          description: Not Found
          schema:
            type: Object
      summary: Update a transaction
      tags:
      - Transactions
    put:
      consumes:
      - application/json
      description: update a transaction fields
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: id
        in: path
        name: id
        required: true
        type: integer
      - description: Transaction to update
        in: body
        name: transaction
        required: true
        schema:
          $ref: '#/definitions/handler.request'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: Object
        "400":
          description: Bad Request
          schema:
            type: Object
        "401":
          description: Unauthorized
          schema:
            type: Object
        "404":
          description: Not Found
          schema:
            type: Object
      summary: Update a transaction
      tags:
      - Transactions
swagger: "2.0"
